// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxzbzyisnificdwtzddc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4emJ6eWlzbmlmaWNkd3R6ZGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTU0MjEsImV4cCI6MjA2MzEzMTQyMX0.EtOn-XpaG-z5S37ooCGEDwYE8nOa836Y7XuKbaS4QsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);